config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
# frozen_string_literal: true

class Cocktail < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
end

app/models/dose.rb
# frozen_string_literal: true

class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :description, presence: true
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
# frozen_string_literal: true

class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktails = Cocktail.all
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def article_params
    params.require(:article).permit(:title, :body, :photo)
  end
end

app/controllers/doses_controller.rb
# frozen_string_literal: true

class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cocktails_helper.rb
# frozen_string_literal: true

module CocktailsHelper
end

app/helpers/doses_helper.rb
# frozen_string_literal: true

module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="bigcontainer">
<div class="container">

<h1>All Cocktails 🍹🍸 </h1>
</div>

<div class="container">

<ul class="anchor">
<% @cocktails.each do |cocktail| %>
<h3 class="anchor">  <%= link_to(cocktail.name.capitalize, cocktail_path(cocktail))  %></h3>
<% end %>
</ul>

</div>

<h4 class="container">
<a href="/cocktails/new">+ Create new cocktail</a>
</h4>

</div>

<%= cl_image_tag("njcamfkr1okut1iw4hyv",
      width: 400, height: 300, crop: :fill) %>

app/views/cocktails/new.html.erb
<div class="bigcontainer">
<h1 class="container">New Cocktail </h1>


<div class="container">
<%= simple_form_for(@cocktail) do |f|  %>
    <%= f.input :name  %> <br>
    <%=f.input :photo, as: :file%>
     <%= f.submit  %>
<% end %>
</div>


<br>
<h4 class="container">
<a href="/cocktails">Back to all Cocktails</a>
</h4>
</div>

app/views/cocktails/show.html.erb
<div class="bigcontainer">
<h1 class="container"> <%=@cocktail.name.capitalize  %>🍹</h1>

</div>


<h6 class="container"> Ingredients: 
<ul> <br>
  <% @cocktail.doses.each do |dose| %>
  <li> <STRONG> <%= dose.ingredient.name.capitalize %> </STRONG> : <%= dose.description %>
  <%= link_to(dose_path(dose), method: :delete, data: { confirm: "ARE YOU SURE ?"}) do %>
    <i> (delete) </i>
    <% end %>
  </li>
  <br>
  <%end  %>
  <br>
  </ul>
</h6> 

<br>
<div class="container">
<%= link_to("Click to Edit", edit_cocktail_path(@cocktail)) %> 
</div>

<div class="container">
<%= link_to("Click to add Ingredient", new_cocktail_dose_path(@cocktail)) %> 
</div>

<h4 class="container">
<a href="/cocktails">Back to all Cocktails</a>
</h4>

</div>

<% if @cocktail.photo.attached? %>
  <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
<% end %>

app/views/doses/new.html.erb
<div class="bigcontainer">
<h1 class="container">New ingredient for <%=@cocktail.name.capitalize %></h1>


<div class="container">
<%= simple_form_for [ @cocktail, @dose ] do |f|  %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.submit  %>
<% end %>
</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>